baseurl = "https://k8.github.io/"
languageCode = "en-us"
title = "About Kate"
theme = "hugo-theme-casper"
background = "bg-Black"
body_classes = "avenir bg-near-white"

paginate = 2
Copyright = "© Dragonetti 2020"
canonifyurls = true
[params]
description = "I'm just a guy dood man making a website to practice for my job."
authorlocation = "authorlocation"
cover = "images/cover.jpeg"
logo = "images/logo.png"
githubName = "kdragonetti"
linkedinName = "your linkedin name"
email = "katedragonetti22@gmail.com"
instagramName = "@katedragon"
hideHUGOSupport = false
[[menu.main]]  # here are the buttons on the menu
name = "Home" # Button will display as "Home"
weight = 100 # the weight decides the position of the button (higher or lower)
identifier = "home"
pre = "<br />"
url = "/"
[[menu.main]]
name = "Contact"
weight = 0
identifier = "contact" # this button will refer to a markdown file named "contact" in the content folder
pre = "<br />"
url = "/contact"
[[menu.main]]
name = "About"
weight = 0
identifier = "about" # this button will refer to a markdown file named "contact" in the content folder
pre = "<br />"
url = "/about"
[[menu.main]]
name = "Writing"
identifier = "writing" # this page will refer to a markdown file named "blog" in the content folder
pre = "<br />"
url = "/writing"
weight = 40
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
